name: Get Random Notion Page

on:
  workflow_dispatch: # Allows manual triggering from a webhook

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python script
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
      id: run_script
      run: |
        URL=$(python main.py)
        echo "::set-output name=page_url::$URL"

    - name: Output the random page URL
      run: echo "Random page URL: ${{ steps.run_script.outputs.page_url }}"
